services:
  - type: web
    plan: free
    name: Image-Editor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https://github.com/Solebot004/Image-Editor.git      
    branch: main
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH
        sync: false
      
      - key: RemoveBG_API
        sync: false
    autoDeploy: false
